### ISSUE TITLE
Allow users to disable rules by filename

### ISSUE THREAD

**Issue by SD10** [kateinoigakukun/IBLinter#32]
In SwiftLint you can disable rules through comments in the source code. This is a little more difficult for storyboards. It would be nice to allow users to turn of specific rules for certain files

**Comment by grantneufeld** [comment]
iirc, SwiftLint’s config file is based on RuboCop. In RuboCop, file-level exclusions are handled in the config yml file like:
```yml
Metrics/BlockLength:
  Exclude:
    - 'my_big_class.rb'
```
In that example, the “Metrics/BlockLength” rule would not be run on the “my_big_class.rb” file.

So, for IBLinter, you might end up with something like this in your `.iblinter.yml` file:
```yml
relative_to_margin:
  Exclude:
    - 'MyMarginedLayout.storyboard'
    - 'App/Base.lproj/AnotherLayoutUsingMargins.storyboard'
```
